//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuat
    {
        public int ID { get; set; }
        public int MaPhieuXuat { get; set; }
        public int MaHang { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
